apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: acs-qe-check
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acs-qe-check 
  name: acs-qe-check
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: acs-qe-check
    weight: 100 
