apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: acs-qe-check
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acs-qe-check 
  name: acs-qe-check
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: acs-qe-check 
